<div class="container">
    <div class="row">
        <h2 class="h2 col-xs-12"><?php $this->sayfabaslikAl(); ?></h2>
    </div>
	<style>
        .github{
            color:darkred;
            font-weight:bold;
            text-decoration:none;
        }
        .github:hover{
            color:orange;
            text-decoration:none;
        }
    </style>
    <div class="row">
        <div class="col-xs-12 col-xs-offset-0 col-md-8 col-md-offset-2">
            <h1 class="h1 text-center" style="color: black; font-weight:bold;">Güzel kod sever misin?</h1>
            <p class="h1 text-center" style="color: black;">
				 Sizlere Mvc Mimarisinde Projeler Geliştirmeyi Sunuyoruz. <br />Web Programcıları İçin PHP Çerçevesi.
            </p>
            <br />
            <a class="github" href="https://github.com/TurkMvc/TurkMvc/tree/TurkMvc" target="_blank">Github TurkMvc</a>
        </div>
    </div>
</div>