<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Navigasyon Menü</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
                <img src="/assets/logo.png" type="image/png" class="pull-left" style="margin-left:-25px; margin-top:-15px; width: 60px; height: 60px;" />&nbsp;&nbsp;
				<strong class="Firma">TürkMvc</strong>
            </a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/">Eklenecek Menu</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/"><i class="glyphicon glyphicon-log-in"></i> Sisteme Giriş</a></li>
                <li><a href="/"><i class="glyphicon glyphicon-pencil"></i> Kayıt OL</a></li>
            </ul>
        </div>
    </div>
</nav>